name: Automatic Deploy Workflow

on:
    push:
        tags:
            - "*"
    workflow_dispatch:

jobs:
    build_and_deploy:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Git checkout
              uses: actions/checkout@v3

            - name: Install dependency and build
              run: |
                  yarn install
                  yarn build

            - name: Deploy to Firebase Hosting
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: "${{ secrets.GITHUB_TOKEN }}"
                  firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_VOTE_7E71D }}"
                  projectId: vote-7e71d
                  channelId: live
